{
 "title": "Monitoring Dash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hoje | Total de Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hoje | Requests 2XX ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"2.*\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hoje | Request 4XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"4.*\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hoje | Requests 5XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"5.*\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Tempo de resposta "
    }
   ]
  },
  {
   "title": "Total de requests per endpoint",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "webapimetric", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Disponibilidade 2XX vs 4XX 5XX",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 - ((sum by (controller) (http_requests_received_total{controller!=\"\", code=~\"4.*|5.*\"})) / (sum by (controller) (http_requests_received_total{controller!=\"\", })) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade 2XX vs 4XX 5XX | últimos 15 minutos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum by (controller) (increase(http_requests_received_total{controller!=\"\", code=~\"4.*|5.*\" }[15m])) / sum by (controller) (increase(http_requests_received_total{controller!=\"\", }[15m]))) * 100)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total Requests per controller",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (increase(http_requests_received_total{controller!=\"\"}[24h]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints mais utilizados nas últimas 24hrs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_requests_received_total{controller!=\"\"}[24h]) > 0",
     "legendFormat": "{{method}} - {{endpoint}} - {{code}}"
    }
   ]
  },
  {
   "title": "Erros 4XX Comparação 7 dias Atrás",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"4.*\"}[4h]))",
     "legendFormat": "Hoje"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"4.*\"}[4h] offset 4h))",
     "legendFormat": "7 dias atrás"
    }
   ]
  },
  {
   "title": "Erros 5XX Comparação 7 dias Atrás",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"5.*\"}[4h]))",
     "legendFormat": "Hoje"
    },
    {
     "expr": "sum(increase(http_requests_received_total{controller!=\"\", code=~\"5.*\"}[4h] offset 4h))",
     "legendFormat": "7 dias atrás"
    }
   ]
  }
 ]
}