global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
  - job_name: servidor
    static_configs:
      - targets:
          - 192.168.18.148:9182
  - job_name: monitoring
    static_configs:
      - targets:
          - 192.168.18.148:5565
